import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/scss/client-styles.scss";
import Header from "@/components/client/header/header";
import { StoreProvider } from "@/redux/StoreProvider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <StoreProvider>
          <Header />
          {children}
          <Toaster />
        </StoreProvider>
      </body>
    </html>
  );
}
