import type { Metadata } from "next";
import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ['latin'] })
import "@/scss/admin-styles.scss";
import "@/scss/client-styles.scss";

import 'bootstrap/dist/css/bootstrap.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
